apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: curator
  namespace: {{ namespace }}
spec:
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Replace
  schedule: 1 0 * * *
  jobTemplate:
    spec:
      template:
        spec:
          nodeSelector:
            NodeType: {{ preferred_node }}
          containers:
          - name: curator
            image: bobrik/curator
            args: ["--config", "/etc/config/config.yml", "/etc/config/action_file.yml"]
            volumeMounts:
              - name: config-volume
                mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: curator-config
          restartPolicy: OnFailure
