kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: es-data-pvc
  annotations:
    volume.beta.kubernetes.io/storage-class: "es-data-storage"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
